name: Check for unused imports using Pylint

on:
  workflow_call:
    inputs:
      languages:
        description: "Optional input to set languages for unused imports check. Supported values are: 'cpp', 'csharp', 'go', 'java', 'javascript', 'typescript', 'python', 'ruby'. To set multiple languages, use the same syntax as you can see in the default value."
        required: false
        type: string
        default: "['python']"

jobs:
  check-unused-imports:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Analysing the code with pylint
        run: | 
          make unused-imports
