name: Check CODEOWNERS File

on:
  pull_request:
    branches:
      - main  # Adjust this to your default branch if different

permissions:
  contents: read
  pull-requests: write

jobs:
  check-codeowners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for CODEOWNERS file and fail if not present
        run: |
          if [ -f "./.github/CODEOWNERS" ]; then
            echo "CODEOWNERS_EXISTS=true" >> $GITHUB_ENV
          else
            echo "CODEOWNERS_EXISTS=false" >> $GITHUB_ENV
            echo "Failing check due to missing CODEOWNERS file."
            exit 1
          fi

      - name: Add PR comment about CODEOWNERS file
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ env.CODEOWNERS_EXISTS == 'true' && '✅ CODEOWNERS file exists.' || '❌ No CODEOWNERS file found.' }}
          token: ${{ secrets.GITHUB_TOKEN }}
