name: Check CODEOWNERS File

on:
  pull_request:
    branches:
      - main  # or your default branch

permissions:
  contents: read
  issues: write  # This permission allows commenting on PRs

jobs:
  check-codeowners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for CODEOWNERS file
        id: check_codeowners
        run: |
          if [ -f ".github/CODEOWNERS" ]; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi

      - name: Add PR comment about CODEOWNERS file
        uses: mshick/add-pr-comment@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          message: |
            ${{ steps.check_codeowners.outputs.exists == 'true' && '✅ CODEOWNERS file exists.' || '❌ No CODEOWNERS file found.' }}
          allow-repeats: false
