name: Check CODEOWNERS File

on:
  pull_request:
    branches:
      - main  # Adjust this to your default branch if different

permissions:
  contents: read
  pull-requests: write

jobs:
  check-codeowners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for CODEOWNERS file
        id: check_codeowners
        run: |
          if [ -f ".github/CODEOWNERS" ]; then
            echo "CODEOWNERS_EXISTS=true" >> $GITHUB_ENV
          else
            echo "CODEOWNERS_EXISTS=false" >> $GITHUB_ENV

      - name: Post PR comment
        if: github.event_name == 'pull_request'
        run: |
          COMMENT_BODY="${{ env.CODEOWNERS_EXISTS == 'true' && '✅ CODEOWNERS file exists.' || '❌ No CODEOWNERS file found.' }}"
          PR_COMMENTS_URL=$(jq -r .pull_request.comments_url "$GITHUB_EVENT_PATH")
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d "{\"body\": \"$COMMENT_BODY\"}" \
               $PR_COMMENTS_URL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
