name: Check for codeowners existence

on:
  pull_request:
    branches:
      - main

jobs:
  check-for-codeowners_existence:
    name: Check codeowners file existence
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check codeowners existence in current repository
        id: check_codeowners_existence_current_repo
        run: |
          CODEOWNERS_FILE_PATH="CODEOWNERS"
          if [[ ! -f "$CODEOWNERS_FILE_PATH" ]]; then
            echo "CODEOWNERS file does not exist in current repository - ${{ github.repository }}."
            echo "CODEOWNERS_STATUS=NOTFOUND" >> $GITHUB_ENV
            exit 1
          else
            echo "CODEOWNERS file exists in current repository. No action needed."
            echo "CODEOWNERS_STATUS=EXISTS" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Add PR comment in current repository
        if: always()
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ env.CODEOWNERS_STATUS == 'NOTFOUND' && '❌ CODEOWNERS File NOTFOUND' || '👍 No issues. CODEOWNERS Exists' }}
          token: ${{ secrets.GITHUB_TOKEN }}
          message-id: "CODEOWNERS_VALIDATION"
          allow-repeats: false
