name: Check CODEOWNERS File

on:
  pull_request:
    branches:
      - main  # Adjust this to your default branch if different

permissions:
  contents: read
  pull-requests: write

jobs:
  check-codeowners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check and Comment on CODEOWNERS file
        run: |
          if [ -f "./.github/CODEOWNERS" ]; then
            CODEOWNERS_EXISTS=true
            COMMENT_BODY="✅ CODEOWNERS file exists."
          else
            CODEOWNERS_EXISTS=false
            COMMENT_BODY="❌ No CODEOWNERS file found."
            echo "No CODEOWNERS file found, failing the check."
            exit 1
          fi
          PR_COMMENTS_URL=$(jq -r .pull_request.comments_url "$GITHUB_EVENT_PATH")
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d "{\"body\": \"$COMMENT_BODY\"}" \
               $PR_COMMENTS_URL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
